// GENERATED BY EVAGEN. DO NOT EDIT.
#include <EVA/Core/Object.hpp>
#include <EVA/Core/Serialization.hpp>
#include <EVA/Core/Allocator.hpp>
#include <EVA/Assets/Asset.hpp>
#include <EVA/Assets/EditorMap.hpp>
#include <EVA/Assets/Font.hpp>
#include <EVA/Assets/Map.hpp>
#include <EVA/Assets/Material.hpp>
#include <EVA/Assets/Mesh.hpp>
#include <EVA/Assets/Model.hpp>
#include <EVA/Assets/Shader.hpp>
#include <EVA/Assets/Sprite.hpp>
#include <EVA/Assets/Texture.hpp>
#include <EVA/GameMode.hpp>
#include <EVA/BasePlayableGameMode.hpp>
#include <EVA/Editor.hpp>

static Type g_type_Object = {
	.parent_type = nullptr,
	.name = "Object",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Object), alignof(Object));
		new (ptr) Object();
		return ptr;
	},};
static Type g_type_Asset = {
	.parent_type = &g_type_Object,
	.name = "Asset",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Asset), alignof(Asset));
		new (ptr) Asset();
		return ptr;
	},};
static Type g_type_EditorMap = {
	.parent_type = &g_type_Asset,
	.name = "EditorMap",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EditorMap), alignof(EditorMap));
		new (ptr) EditorMap();
		return ptr;
	},};
static Type g_type_Font = {
	.parent_type = &g_type_Asset,
	.name = "Font",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Font), alignof(Font));
		new (ptr) Font();
		return ptr;
	},};
static Type g_type_Map = {
	.parent_type = &g_type_Asset,
	.name = "Map",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Map), alignof(Map));
		new (ptr) Map();
		return ptr;
	},};
static Type g_type_Material = {
	.parent_type = &g_type_Asset,
	.name = "Material",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Material), alignof(Material));
		new (ptr) Material();
		return ptr;
	},};
static Type g_type_Mesh = {
	.parent_type = &g_type_Asset,
	.name = "Mesh",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Mesh), alignof(Mesh));
		new (ptr) Mesh();
		return ptr;
	},};
static Type g_type_Model = {
	.parent_type = &g_type_Asset,
	.name = "Model",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Model), alignof(Model));
		new (ptr) Model();
		return ptr;
	},};
static Type g_type_Shader = {
	.parent_type = &g_type_Asset,
	.name = "Shader",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Shader), alignof(Shader));
		new (ptr) Shader();
		return ptr;
	},};
static Type g_type_Sprite = {
	.parent_type = &g_type_Asset,
	.name = "Sprite",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Sprite), alignof(Sprite));
		new (ptr) Sprite();
		return ptr;
	},};
static Type g_type_Texture = {
	.parent_type = &g_type_Asset,
	.name = "Texture",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Texture), alignof(Texture));
		new (ptr) Texture();
		return ptr;
	},};
static Type g_type_GameMode = {
	.parent_type = &g_type_Object,
	.name = "GameMode",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(GameMode), alignof(GameMode));
		new (ptr) GameMode();
		return ptr;
	},};
static Type g_type_BasePlayableGameMode = {
	.parent_type = &g_type_GameMode,
	.name = "BasePlayableGameMode",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(BasePlayableGameMode), alignof(BasePlayableGameMode));
		new (ptr) BasePlayableGameMode();
		return ptr;
	},};
static Type g_type_EditorGameMode = {
	.parent_type = &g_type_GameMode,
	.name = "EditorGameMode",
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EditorGameMode), alignof(EditorGameMode));
		new (ptr) EditorGameMode();
		return ptr;
	},};

Type* Object::StaticClass() { return &g_type_Object; }
Type* Object::GetClass() { return &g_type_Object; }
Type* Asset::StaticClass() { return &g_type_Asset; }
Type* Asset::GetClass() { return &g_type_Asset; }
Type* EditorMap::StaticClass() { return &g_type_EditorMap; }
Type* EditorMap::GetClass() { return &g_type_EditorMap; }
Type* Font::StaticClass() { return &g_type_Font; }
Type* Font::GetClass() { return &g_type_Font; }
Type* Map::StaticClass() { return &g_type_Map; }
Type* Map::GetClass() { return &g_type_Map; }
Type* Material::StaticClass() { return &g_type_Material; }
Type* Material::GetClass() { return &g_type_Material; }
Type* Mesh::StaticClass() { return &g_type_Mesh; }
Type* Mesh::GetClass() { return &g_type_Mesh; }
Type* Model::StaticClass() { return &g_type_Model; }
Type* Model::GetClass() { return &g_type_Model; }
Type* Shader::StaticClass() { return &g_type_Shader; }
Type* Shader::GetClass() { return &g_type_Shader; }
Type* Sprite::StaticClass() { return &g_type_Sprite; }
Type* Sprite::GetClass() { return &g_type_Sprite; }
Type* Texture::StaticClass() { return &g_type_Texture; }
Type* Texture::GetClass() { return &g_type_Texture; }
Type* GameMode::StaticClass() { return &g_type_GameMode; }
Type* GameMode::GetClass() { return &g_type_GameMode; }
Type* BasePlayableGameMode::StaticClass() { return &g_type_BasePlayableGameMode; }
Type* BasePlayableGameMode::GetClass() { return &g_type_BasePlayableGameMode; }
Type* EditorGameMode::StaticClass() { return &g_type_EditorGameMode; }
Type* EditorGameMode::GetClass() { return &g_type_EditorGameMode; }

Type* Type::Find(String name) {
	static Type* all[] = {
		&g_type_Object,
		&g_type_Asset,
		&g_type_EditorMap,
		&g_type_Font,
		&g_type_Map,
		&g_type_Material,
		&g_type_Mesh,
		&g_type_Model,
		&g_type_Shader,
		&g_type_Sprite,
		&g_type_Texture,
		&g_type_GameMode,
		&g_type_BasePlayableGameMode,
		&g_type_EditorGameMode,
	};
	for (Type* t : all)
		if (name == t->name) return t;
	return nullptr;
}
void Serialize(Serializer& s, const TextureInterpolation& value);
void Deserialize(Deserializer& s, TextureInterpolation& out_value);
void Serialize(Serializer& s, const TextureWrapMode& value);
void Deserialize(Deserializer& s, TextureWrapMode& out_value);
void Serialize(Serializer& s, const TextureProps& value);
void Deserialize(Deserializer& s, TextureProps& out_value);

void Serialize(Serializer& s, const TextureInterpolation& value) {
	Serialize(s, (U8)value);
}

void Deserialize(Deserializer& s, TextureInterpolation& out_value) {
	U8 tmp = {};
	Deserialize(s, tmp);
	out_value = (TextureInterpolation)tmp;
}

void Serialize(Serializer& s, const TextureWrapMode& value) {
	Serialize(s, (U8)value);
}

void Deserialize(Deserializer& s, TextureWrapMode& out_value) {
	U8 tmp = {};
	Deserialize(s, tmp);
	out_value = (TextureWrapMode)tmp;
}

void Serialize(Serializer& s, const TextureProps& value) {
	s.BeginObject();
	s.Key("generate_mipmaps");
	Serialize(s, value.generate_mipmaps);
	s.Key("interpolation");
	Serialize(s, value.interpolation);
	s.Key("wrap_mode");
	Serialize(s, value.wrap_mode);
	s.EndObject();
}

void Deserialize(Deserializer& s, TextureProps& out_value) {
	s.BeginObject();
	s.Key("generate_mipmaps");
	Deserialize(s, out_value.generate_mipmaps);
	s.Key("interpolation");
	Deserialize(s, out_value.interpolation);
	s.Key("wrap_mode");
	Deserialize(s, out_value.wrap_mode);
	s.EndObject();
}
