// GENERATED BY EVAGEN. DO NOT EDIT.
#include <EVA/Core/Object.hpp>
#include <EVA/Core/Serialization.hpp>
#include <EVA/Core/Allocator.hpp>
#include <EVA/Core/Object.hpp>
#include <EVA/Assets/Asset.hpp>
#include <EVA/Assets/EditorMap.hpp>
#include <EVA/Assets/Font.hpp>
#include <EVA/Assets/Map.hpp>
#include <EVA/Assets/Material.hpp>
#include <EVA/Assets/Mesh.hpp>
#include <EVA/Assets/Model.hpp>
#include <EVA/Assets/Shader.hpp>
#include <EVA/Assets/Sprite.hpp>
#include <EVA/Assets/Texture.hpp>
#include <EVA/Assets/Texture.hpp>
#include <EVA/Assets/Texture.hpp>
#include <EVA/Assets/Texture.hpp>
#include <EVA/Entities/Entity.hpp>
#include <EVA/Editor/Editor.hpp>
#include <EVA/Editor/Editor.hpp>
#include <EVA/Editor/Editor.hpp>
#include <EVA/Editor/Editor.hpp>
#include <EVA/Entities/ECamera.hpp>
#include <EVA/Entities/ECharacter.hpp>
#include <EVA/Entities/EMarker.hpp>
#include <EVA/GameModes/GameMode.hpp>
#include <EVA/GameModes/BasePlayableGameMode.hpp>
#include <EVA/GameModes/EditorGameMode.hpp>

extern Type g_type_Object;
extern Type g_type_Asset;
extern Type g_type_EditorMap;
extern Type g_type_Font;
extern Type g_type_Map;
extern Type g_type_Material;
extern Type g_type_Mesh;
extern Type g_type_Model;
extern Type g_type_Shader;
extern Type g_type_Sprite;
extern Type g_type_TextureInterpolation;
extern Type g_type_TextureWrapMode;
extern Type g_type_TextureProps;
extern Type g_type_Texture;
extern Type g_type_Entity;
extern Type g_type_Tool;
extern Type g_type_SelectTool;
extern Type g_type_EntityTool;
extern Type g_type_BrushTool;
extern Type g_type_ECamera;
extern Type g_type_ECharacter;
extern Type g_type_EMarker;
extern Type g_type_GameMode;
extern Type g_type_BasePlayableGameMode;
extern Type g_type_EditorGameMode;


Type g_type_Object = {
	.name = "Object",
	.parent_type = nullptr,
	.subclasses = {
		&g_type_Asset,
		&g_type_Entity,
		&g_type_Tool,
		&g_type_GameMode,
	},
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Object), alignof(Object));
		new (ptr) Object();
		return ptr;
	},
};
Type g_type_Asset = {
	.name = "Asset",
	.parent_type = &g_type_Object,
	.subclasses = {
		&g_type_EditorMap,
		&g_type_Font,
		&g_type_Map,
		&g_type_Material,
		&g_type_Mesh,
		&g_type_Model,
		&g_type_Shader,
		&g_type_Sprite,
		&g_type_Texture,
	},
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Asset), alignof(Asset));
		new (ptr) Asset();
		return ptr;
	},
};
Type g_type_EditorMap = {
	.name = "EditorMap",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EditorMap), alignof(EditorMap));
		new (ptr) EditorMap();
		return ptr;
	},
};
Type g_type_Font = {
	.name = "Font",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Font), alignof(Font));
		new (ptr) Font();
		return ptr;
	},
};
Type g_type_Map = {
	.name = "Map",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Map), alignof(Map));
		new (ptr) Map();
		return ptr;
	},
};
Type g_type_Material = {
	.name = "Material",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Material), alignof(Material));
		new (ptr) Material();
		return ptr;
	},
};
Type g_type_Mesh = {
	.name = "Mesh",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Mesh), alignof(Mesh));
		new (ptr) Mesh();
		return ptr;
	},
};
Type g_type_Model = {
	.name = "Model",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Model), alignof(Model));
		new (ptr) Model();
		return ptr;
	},
};
Type g_type_Shader = {
	.name = "Shader",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Shader), alignof(Shader));
		new (ptr) Shader();
		return ptr;
	},
};
Type g_type_Sprite = {
	.name = "Sprite",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Sprite), alignof(Sprite));
		new (ptr) Sprite();
		return ptr;
	},
};
Type g_type_TextureInterpolation = {
	.name = "TextureInterpolation",
	.parent_type = nullptr,
};
Type g_type_TextureWrapMode = {
	.name = "TextureWrapMode",
	.parent_type = nullptr,
};
Type g_type_TextureProps = {
	.name = "TextureProps",
	.parent_type = nullptr,
};
Type g_type_Texture = {
	.name = "Texture",
	.parent_type = &g_type_Asset,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Texture), alignof(Texture));
		new (ptr) Texture();
		return ptr;
	},
};
Type g_type_Entity = {
	.name = "Entity",
	.parent_type = &g_type_Object,
	.subclasses = {
		&g_type_ECamera,
		&g_type_ECharacter,
		&g_type_EMarker,
	},
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(Entity), alignof(Entity));
		new (ptr) Entity();
		return ptr;
	},
};
Type g_type_Tool = {
	.name = "Tool",
	.parent_type = &g_type_Object,
	.subclasses = {
		&g_type_SelectTool,
		&g_type_EntityTool,
		&g_type_BrushTool,
	},
};
Type g_type_SelectTool = {
	.name = "SelectTool",
	.parent_type = &g_type_Tool,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(SelectTool), alignof(SelectTool));
		new (ptr) SelectTool();
		return ptr;
	},
};
Type g_type_EntityTool = {
	.name = "EntityTool",
	.parent_type = &g_type_Tool,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EntityTool), alignof(EntityTool));
		new (ptr) EntityTool();
		return ptr;
	},
};
Type g_type_BrushTool = {
	.name = "BrushTool",
	.parent_type = &g_type_Tool,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(BrushTool), alignof(BrushTool));
		new (ptr) BrushTool();
		return ptr;
	},
};
Type g_type_ECamera = {
	.name = "ECamera",
	.parent_type = &g_type_Entity,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(ECamera), alignof(ECamera));
		new (ptr) ECamera();
		return ptr;
	},
};
Type g_type_ECharacter = {
	.name = "ECharacter",
	.parent_type = &g_type_Entity,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(ECharacter), alignof(ECharacter));
		new (ptr) ECharacter();
		return ptr;
	},
};
Type g_type_EMarker = {
	.name = "EMarker",
	.parent_type = &g_type_Entity,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EMarker), alignof(EMarker));
		new (ptr) EMarker();
		return ptr;
	},
};
Type g_type_GameMode = {
	.name = "GameMode",
	.parent_type = &g_type_Object,
	.subclasses = {
		&g_type_BasePlayableGameMode,
		&g_type_EditorGameMode,
	},
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(GameMode), alignof(GameMode));
		new (ptr) GameMode();
		return ptr;
	},
};
Type g_type_BasePlayableGameMode = {
	.name = "BasePlayableGameMode",
	.parent_type = &g_type_GameMode,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(BasePlayableGameMode), alignof(BasePlayableGameMode));
		new (ptr) BasePlayableGameMode();
		return ptr;
	},
};
Type g_type_EditorGameMode = {
	.name = "EditorGameMode",
	.parent_type = &g_type_GameMode,
	.Instantiate = [](Allocator allocator) -> void* {
		void* ptr = (void*)allocator.Allocate(sizeof(EditorGameMode), alignof(EditorGameMode));
		new (ptr) EditorGameMode();
		return ptr;
	},
};

Type* Object::StaticClass() { return &g_type_Object; }
Type* Object::GetClass() { return &g_type_Object; }
Type* Asset::StaticClass() { return &g_type_Asset; }
Type* Asset::GetClass() { return &g_type_Asset; }
Type* EditorMap::StaticClass() { return &g_type_EditorMap; }
Type* EditorMap::GetClass() { return &g_type_EditorMap; }
Type* Font::StaticClass() { return &g_type_Font; }
Type* Font::GetClass() { return &g_type_Font; }
Type* Map::StaticClass() { return &g_type_Map; }
Type* Map::GetClass() { return &g_type_Map; }
Type* Material::StaticClass() { return &g_type_Material; }
Type* Material::GetClass() { return &g_type_Material; }
Type* Mesh::StaticClass() { return &g_type_Mesh; }
Type* Mesh::GetClass() { return &g_type_Mesh; }
Type* Model::StaticClass() { return &g_type_Model; }
Type* Model::GetClass() { return &g_type_Model; }
Type* Shader::StaticClass() { return &g_type_Shader; }
Type* Shader::GetClass() { return &g_type_Shader; }
Type* Sprite::StaticClass() { return &g_type_Sprite; }
Type* Sprite::GetClass() { return &g_type_Sprite; }
Type* Texture::StaticClass() { return &g_type_Texture; }
Type* Texture::GetClass() { return &g_type_Texture; }
Type* Entity::StaticClass() { return &g_type_Entity; }
Type* Entity::GetClass() { return &g_type_Entity; }
Type* Tool::StaticClass() { return &g_type_Tool; }
Type* Tool::GetClass() { return &g_type_Tool; }
Type* SelectTool::StaticClass() { return &g_type_SelectTool; }
Type* SelectTool::GetClass() { return &g_type_SelectTool; }
Type* EntityTool::StaticClass() { return &g_type_EntityTool; }
Type* EntityTool::GetClass() { return &g_type_EntityTool; }
Type* BrushTool::StaticClass() { return &g_type_BrushTool; }
Type* BrushTool::GetClass() { return &g_type_BrushTool; }
Type* ECamera::StaticClass() { return &g_type_ECamera; }
Type* ECamera::GetClass() { return &g_type_ECamera; }
Type* ECharacter::StaticClass() { return &g_type_ECharacter; }
Type* ECharacter::GetClass() { return &g_type_ECharacter; }
Type* EMarker::StaticClass() { return &g_type_EMarker; }
Type* EMarker::GetClass() { return &g_type_EMarker; }
Type* GameMode::StaticClass() { return &g_type_GameMode; }
Type* GameMode::GetClass() { return &g_type_GameMode; }
Type* BasePlayableGameMode::StaticClass() { return &g_type_BasePlayableGameMode; }
Type* BasePlayableGameMode::GetClass() { return &g_type_BasePlayableGameMode; }
Type* EditorGameMode::StaticClass() { return &g_type_EditorGameMode; }
Type* EditorGameMode::GetClass() { return &g_type_EditorGameMode; }

Type* Type::Find(String name) {
	static Type* g_allTypes[] = {
		&g_type_Object,
		&g_type_Asset,
		&g_type_EditorMap,
		&g_type_Font,
		&g_type_Map,
		&g_type_Material,
		&g_type_Mesh,
		&g_type_Model,
		&g_type_Shader,
		&g_type_Sprite,
		&g_type_TextureInterpolation,
		&g_type_TextureWrapMode,
		&g_type_TextureProps,
		&g_type_Texture,
		&g_type_Entity,
		&g_type_Tool,
		&g_type_SelectTool,
		&g_type_EntityTool,
		&g_type_BrushTool,
		&g_type_ECamera,
		&g_type_ECharacter,
		&g_type_EMarker,
		&g_type_GameMode,
		&g_type_BasePlayableGameMode,
		&g_type_EditorGameMode,
	};
	for (Type* t : g_allTypes)
		if (name == t->name) return t;
	return nullptr;
}
void Serialize(Serializer& s, const TextureInterpolation& value);
void Deserialize(Deserializer& s, TextureInterpolation& out_value);
void Serialize(Serializer& s, const TextureWrapMode& value);
void Deserialize(Deserializer& s, TextureWrapMode& out_value);
void Serialize(Serializer& s, const TextureProps& value);
void Deserialize(Deserializer& s, TextureProps& out_value);



void Serialize(Serializer& s, const TextureInterpolation& value) {
	Serialize(s, (U8)value);
}

void Deserialize(Deserializer& s, TextureInterpolation& out_value) {
	U8 tmp = {};
	Deserialize(s, tmp);
	out_value = (TextureInterpolation)tmp;
}

void Serialize(Serializer& s, const TextureWrapMode& value) {
	Serialize(s, (U8)value);
}

void Deserialize(Deserializer& s, TextureWrapMode& out_value) {
	U8 tmp = {};
	Deserialize(s, tmp);
	out_value = (TextureWrapMode)tmp;
}

void Serialize(Serializer& s, const TextureProps& value) {
	s.BeginObject();
	s.Key("generate_mipmaps");
	Serialize(s, value.generate_mipmaps);
	s.Key("interpolation");
	Serialize(s, value.interpolation);
	s.Key("wrap_mode");
	Serialize(s, value.wrap_mode);
	s.EndObject();
}

void Deserialize(Deserializer& s, TextureProps& out_value) {
	s.BeginObject();
	s.Key("generate_mipmaps");
	Deserialize(s, out_value.generate_mipmaps);
	s.Key("interpolation");
	Deserialize(s, out_value.interpolation);
	s.Key("wrap_mode");
	Deserialize(s, out_value.wrap_mode);
	s.EndObject();
}
