// GENERATED BY EVAGEN. DO NOT EDIT.
#include <EVA/Object.hpp>
#include <EVA/Assets/Asset.hpp>
#include <EVA/Assets/EditorMap.hpp>
#include <EVA/Assets/Font.hpp>
#include <EVA/Assets/GLTF.hpp>
#include <EVA/Assets/Map.hpp>
#include <EVA/Assets/Material.hpp>
#include <EVA/Assets/Mesh.hpp>
#include <EVA/Assets/Shader.hpp>
#include <EVA/Assets/Sprite.hpp>
#include <EVA/Assets/Texture.hpp>

static Type g_type_Object = {
	.parent_type = nullptr,
	.name = "Object",
	.Instantiate = []() -> Object* { return new Object(); },
};
static Type g_type_Asset = {
	.parent_type = &g_type_Object,
	.name = "Asset",
	.Instantiate = []() -> Object* { return new Asset(); },
};
static Type g_type_EditorMap = {
	.parent_type = &g_type_Asset,
	.name = "EditorMap",
	.Instantiate = []() -> Object* { return new EditorMap(); },
};
static Type g_type_Font = {
	.parent_type = &g_type_Asset,
	.name = "Font",
	.Instantiate = []() -> Object* { return new Font(); },
};
static Type g_type_GLTF = {
	.parent_type = &g_type_Asset,
	.name = "GLTF",
	.Instantiate = []() -> Object* { return new GLTF(); },
};
static Type g_type_Map = {
	.parent_type = &g_type_Asset,
	.name = "Map",
	.Instantiate = []() -> Object* { return new Map(); },
};
static Type g_type_Material = {
	.parent_type = &g_type_Asset,
	.name = "Material",
	.Instantiate = []() -> Object* { return new Material(); },
};
static Type g_type_Mesh = {
	.parent_type = &g_type_Asset,
	.name = "Mesh",
	.Instantiate = []() -> Object* { return new Mesh(); },
};
static Type g_type_Shader = {
	.parent_type = &g_type_Asset,
	.name = "Shader",
	.Instantiate = []() -> Object* { return new Shader(); },
};
static Type g_type_Sprite = {
	.parent_type = &g_type_Asset,
	.name = "Sprite",
	.Instantiate = []() -> Object* { return new Sprite(); },
};
static Type g_type_Texture = {
	.parent_type = &g_type_Asset,
	.name = "Texture",
	.Instantiate = []() -> Object* { return new Texture(); },
};

Type* Object::StaticClass() { return &g_type_Object; }
Type* Object::GetClass() { return &g_type_Object; }
Type* Asset::StaticClass() { return &g_type_Asset; }
Type* Asset::GetClass() { return &g_type_Asset; }
Type* EditorMap::StaticClass() { return &g_type_EditorMap; }
Type* EditorMap::GetClass() { return &g_type_EditorMap; }
Type* Font::StaticClass() { return &g_type_Font; }
Type* Font::GetClass() { return &g_type_Font; }
Type* GLTF::StaticClass() { return &g_type_GLTF; }
Type* GLTF::GetClass() { return &g_type_GLTF; }
Type* Map::StaticClass() { return &g_type_Map; }
Type* Map::GetClass() { return &g_type_Map; }
Type* Material::StaticClass() { return &g_type_Material; }
Type* Material::GetClass() { return &g_type_Material; }
Type* Mesh::StaticClass() { return &g_type_Mesh; }
Type* Mesh::GetClass() { return &g_type_Mesh; }
Type* Shader::StaticClass() { return &g_type_Shader; }
Type* Shader::GetClass() { return &g_type_Shader; }
Type* Sprite::StaticClass() { return &g_type_Sprite; }
Type* Sprite::GetClass() { return &g_type_Sprite; }
Type* Texture::StaticClass() { return &g_type_Texture; }
Type* Texture::GetClass() { return &g_type_Texture; }
