#pragma once
#include <EVA/Core/Common.hpp>
#include <EVA/Core/String.hpp>
#include <EVA/Core/Result.hpp>
#include <EVA/Core/Vector.hpp>

#ifdef EVAGEN
#	define EAUTO          [[clang::annotate("eauto")]]
#	define EVERSION(...)  [[clang::annotate("eversion, " #__VA_ARGS__)]]
#else
#	define EVERSION(...)
#	define EAUTO
#endif

struct Allocator;
class Object;
class Serializer;
class Deserializer;

/**
 ** Reflected type info for a type, tracked by the object model.
 ** Values of this are auto-generated by EVAGEN in EVA.gen.cpp
 ** 
 ** For Object-derived classes, you can get this form MyClassName::StaticClass(),
 ** or via the virtual myClassInstance->GetClass().
 **
 ** You can iterate all subclasses of a class via `MyClass::Staticclass()->subclasses`
 **
 ** defaultObject is an automatically-generated direct instance of the class (if it's not abstract)
 ** You can use it to do static virtuals - e.g.
 **       class Parent : Object { virtual void StaticVirtual(); }
 **       class Child : Parent { virtual void StaticVirtual() override; }
 **       for (Type* childClass : Parent::StaticClass()->subclasses) {
 **           ((Parent*)childClass->defaultObject)->StaticVirtual();
 **       }
 **/
class Type {
public:
	ZTString           name          = {};
	Type*              parent_type   = nullptr;
	Vector<Type*>      subclasses    = {};
	void*              defaultObject = {};

	void* (*Instantiate)(Allocator allocator) = nullptr;
	static Type* Find(String name);
};

struct EnumValue {
	ZTString string = {};
	I64      value  = 0;
};

class EnumType : public Type {
public:
	Vector<EnumValue> values = {};

	EnumType(ZTString name, Vector<EnumValue> values) : values(values) {
		this->name = name;
	}
};

/**
 ** Object is the base class tracked by the object model.
 ** If you're making something long-lived with a vtable you probably want to extend this.
 **/
class Object {
public:
	static Type* StaticClass();
	static Object* StaticDefaultObject() { return (Object*)StaticClass()->defaultObject; }
	virtual Type* GetClass();
	virtual ~Object() {}
};


/**
 ** EAUTO_SERIALIZE
 ** Forward declare Serialize/Deserialize functions for a type and request auto-generated implementations.
 ** This handles versioning - see usages of EVERSION macro.
 **
 ** @TODO: The fact that these has to be outside namespaces is fucking stupid.
 **/
#define EAUTO_SERIALIZE(T) \
	EAUTO void Serialize(Serializer& s, const T& value); \
	EAUTO void Deserialize(Deserializer& d, T& value);

/**
 ** EAUTO_ENUM - Register an enum with the object model.
 ** This gives you Serialize/Deserialize/ToString/FromString for this enum.
 **/
#define EAUTO_ENUM(T) \
	EAUTO_SERIALIZE(T) \
	EAUTO ZTString ToString(T& t); \
	template<> EAUTO T FromString<T>(String str);


/**
 ** For classes that extend Object, put an ECLASS_COMMON(MyClass) in the class's body. The object model will
 ** auto-generate implementations for these
 **/
#define ECLASS_COMMON(T) \
	static Type* StaticClass(); \
	static T* StaticDefaultObject() { return (T*)StaticClass()->defaultObject; } \
	virtual Type* GetClass() override;


// @TODO: Update this thing's signature to avoid the template.
template<typename T>
T FromString(String str);