#include <clang-c/Index.h>

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>

namespace fs = std::filesystem;

struct VersionChain;
struct Type;

struct Auto {
	std::string name;
	void (*ForwardDeclare)(FILE* f, Type* type) = 0;
	void (*Declare)(FILE* f, Type* type) = 0;
};

struct Type {
	std::string              name                  = "";
	std::string              qualifiedName         = "";
	std::string              symbolName            = "";
	Type*                    parent                = nullptr;
	std::vector<Type*>       subclasses            = {};
	std::string              header                = "'";
	std::vector<std::string> properties            = {};
	std::vector<Auto*>       autos                 = {};
	bool                     isObject              = false;
	bool                     isAbstract            = false;
	bool                     isEnum                = false;
	std::string              enumUnderlyingType    = "";
	int                      version               = 0;
	VersionChain*            versionChain          = nullptr;
	bool                     shouldEmitTypeInfo    = false;
};

struct VersionChain {
	std::string typeName;
	std::vector<Type*> versions;

	void Set(int version, Type* type) {
		if (versions.size() <= version) {
			versions.resize(version + 1);
		}
		versions[version] = type;
	}
};

// Root that <EVA/...> includes resolve against, and the dir we walk.
static const char* g_baseDir = "D:/EVA";

Auto g_serializeAuto = {
	.name = "Serialize",
	.ForwardDeclare = [](FILE* f, Type* type) {
		fprintf(f, "void Serialize(Serializer& s, const %s& value);\n", type->qualifiedName.c_str());
	},
	.Declare = [](FILE* f, Type* type) {

		if (type->isEnum) {
			fprintf(f, "\nvoid Serialize(Serializer& s, const %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\tSerialize(s, (%s)value);\n", type->enumUnderlyingType.c_str());
			fprintf(f, "}\n");
		} else {
			fprintf(f, "\nvoid Serialize(Serializer& s, const %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\ts.BeginObject();\n");
			for (const std::string& p : type->properties) {
				fprintf(f, "\ts.Key(\"%s\");\n", p.c_str());
				fprintf(f, "\tSerialize(s, value.%s);\n", p.c_str());
			}
			fprintf(f, "\ts.EndObject();\n");
			fprintf(f, "}\n");
		}
	},
};

Auto g_deserializeAuto = {
	.name = "Deserialize",
	.ForwardDeclare = [](FILE* f, Type* type) {
		fprintf(f, "void Deserialize(Serializer& s, %s& value);\n", type->qualifiedName.c_str());
	},
	.Declare = [](FILE* f, Type* type) {
		if (type->isEnum) {
			fprintf(f, "\nvoid Serialize(Serializer& s, const %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\tSerialize(s, (%s)value);\n", type->enumUnderlyingType.c_str());
			fprintf(f, "}\n");

			fprintf(f, "\nvoid Deserialize(Deserializer& d, %s& out_value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\type%s tmp = {};\n", type->enumUnderlyingType.c_str());
			fprintf(f, "\tDeserialize(s, tmp);\n");
			fprintf(f, "\tout_value = (%s)tmp;\n", type->qualifiedName.c_str());
			fprintf(f, "}\n");
		} else {
			fprintf(f, "\nvoid Serialize(Serializer& s, const %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\ts.BeginObject();\n");
			for (const std::string& p : type->properties) {
				fprintf(f, "\ts.Key(\"%s\");\n", p.c_str());
				fprintf(f, "\tSerialize(s, value.%s);\n", p.c_str());
			}
			fprintf(f, "\ts.EndObject();\n");
			fprintf(f, "}\n");

			fprintf(f, "\nvoid Deserialize(Deserializer& d, %s& out_value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\ts.BeginObject();\n");
			for (const std::string& p : type->properties) {
				fprintf(f, "\ts.Key(\"%s\");\n", p.c_str());
				fprintf(f, "\tDeserialize(s, out_value.%s);\n", p.c_str());
			}
			fprintf(f, "\ts.EndObject();\n");
			fprintf(f, "}\n");
		}
	},
};

std::vector<std::string> g_includes = {
	"EVA/Core/Object.hpp",
	"EVA/Core/Serialization.hpp",
	"EVA/Core/Allocator.hpp"
};

static std::string ToForwardSlashes(std::string s) {
	for (char& c : s) if (c == '\\') c = '/';
	return s;
}

static std::vector<std::string> CollectHeaders() {
	std::vector<std::string> headers;

	fs::path base = g_baseDir;
	fs::path walk = base / "EVA";

	for (const auto& entry : fs::recursive_directory_iterator(walk)) {
		if (!entry.is_regular_file()) continue;
		if (entry.path().extension() != ".hpp") continue;

		fs::path rel = fs::relative(entry.path(), base);
		headers.push_back(ToForwardSlashes(rel.string()));
	}

	std::sort(headers.begin(), headers.end());
	return headers;
}

static std::string WriteAmalgam(const std::vector<std::string>& headers) {
	fs::path out = fs::path(g_baseDir) / "EVAGEN" / "_amalgam.generated.hpp";

	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		exit(1);
	}

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	fprintf(f, "#pragma once\n");
	for (const std::string& h : headers) {
		fprintf(f, "#include <%s>\n", h.c_str());
	}
	fclose(f);

	return ToForwardSlashes(out.string());
}

static std::string CXStr(CXString clangString) {
	const char* string = clang_getCString(clangString);
	std::string out = string ? string : "";
	clang_disposeString(clangString);
	return out;
}

// Only report definitions that live inside our source tree, not system headers
// dragged in transitively.
static bool IsInOurTree(CXCursor cursor) {
	CXSourceLocation loc = clang_getCursorLocation(cursor);
	CXFile file;
	clang_getFileLocation(loc, &file, nullptr, nullptr, nullptr);
	if (!file) return false;

	std::string path = ToForwardSlashes(CXStr(clang_getFileName(file)));
	std::string base = ToForwardSlashes(std::string(g_baseDir) + "/EVA/");
	return path.rfind(base, 0) == 0;
}

static std::vector<Type*> g_types;
static std::vector<Type*> g_typesWeCareAbout;

static std::string SymbolName(std::string name) {
	for (char& c : name) {
		if (!isalnum((unsigned char)c) && c != '_') c = '_';
	}
	return name;
}

static Type* GetType(const std::string& qualifiedName, bool* out_alreadyVisited = nullptr) {
	if (out_alreadyVisited) *out_alreadyVisited = false;

	for (Type* type : g_types) {
		if (type->qualifiedName == qualifiedName) {
			if (out_alreadyVisited) *out_alreadyVisited = true;
			return type;
		}
	}

	Type* type = new Type();
	type->qualifiedName = qualifiedName;
	size_t separator = qualifiedName.rfind("::");
	type->name = separator == std::string::npos ? qualifiedName : qualifiedName.substr(separator + 2);
	type->symbolName = SymbolName(qualifiedName);
	g_types.push_back(type);
	return type;
}

static std::string RelToBase(const std::string& path) {
	std::string base = ToForwardSlashes(std::string(g_baseDir)) + "/";
	if (path.rfind(base, 0) == 0) return path.substr(base.size());
	return path;
}

static std::string StripRecordKeyword(std::string s) {
	const char* prefixes[] = { "class ", "struct " };
	for (const char* p : prefixes) {
		size_t n = strlen(p);
		if (s.compare(0, n, p) == 0) { s.erase(0, n); break; }
	}
	return s;
}

static CXChildVisitResult FieldAnnotationVisitor(CXCursor c, CXCursor, CXClientData data) {
	bool* is_prop = (bool*)data;
	if (clang_getCursorKind(c) == CXCursor_AnnotateAttr) {
		std::string s = CXStr(clang_getCursorSpelling(c));
		if (s.rfind("eproperty", 0) == 0) *is_prop = true;
	}
	return CXChildVisit_Continue;
}

static CXChildVisitResult RecordChildVisitor(CXCursor cursor, CXCursor, void* _type) {
	Type* type = (Type*)_type;
	CXCursorKind kind = clang_getCursorKind(cursor);

	if (kind == CXCursor_AnnotateAttr) {
		std::string s = CXStr(clang_getCursorSpelling(cursor));
		// if (s.rfind("eserializable", 0) == 0) {
		// 	info->has_eserializable = true;
		// }
	} else if (kind == CXCursor_CXXBaseSpecifier) {
		CXType base_type = clang_getCanonicalType(clang_getCursorType(cursor));
		type->parent = GetType(StripRecordKeyword(CXStr(clang_getTypeSpelling(base_type))));
		type->parent->subclasses.push_back(type);
	} else if (kind == CXCursor_FieldDecl) {
		bool is_prop = false;
		clang_visitChildren(cursor, FieldAnnotationVisitor, &is_prop);
		if (is_prop) type->properties.push_back(CXStr(clang_getCursorSpelling(cursor)));
	}
	return CXChildVisit_Continue;
}

static CXChildVisitResult Visit(CXCursor cursor, CXCursor parent, void* userdata) {
	CXCursorKind kind = clang_getCursorKind(cursor);

	bool is_record = kind == CXCursor_StructDecl || kind == CXCursor_ClassDecl;
	bool isEnum   = kind == CXCursor_EnumDecl;

	// Only actual definitions (skip forward declarations), and only ours.
	if ((is_record || isEnum) && clang_isCursorDefinition(cursor) && IsInOurTree(cursor)) {

		CXSourceLocation loc = clang_getCursorLocation(cursor);
		CXFile file;
		unsigned line = 0;
		clang_getFileLocation(loc, &file, &line, nullptr, nullptr);

		std::string name = CXStr(clang_getCursorSpelling(cursor));
		std::string qualifiedName = StripRecordKeyword(CXStr(clang_getTypeSpelling(clang_getCursorType(cursor))));
		std::string filename = ToForwardSlashes(CXStr(clang_getFileName(file)));

		bool alreadyVisited = false;
		Type* type = GetType(qualifiedName, &alreadyVisited);
		clang_visitChildren(cursor, RecordChildVisitor, type);
		type->isAbstract = clang_CXXRecord_isAbstract(cursor);
		type->isObject = qualifiedName == "Object" || (type->parent && type->parent->isObject);
		type->header = RelToBase(filename);
		type->isEnum = isEnum;

		if (!alreadyVisited) {
			if (type->isObject) {
				g_typesWeCareAbout.push_back(type);
				g_includes.push_back(filename);
			}
		}

		if (isEnum) 
			type->enumUnderlyingType = CXStr(clang_getTypeSpelling(clang_getEnumDeclIntegerType(cursor)));
	}

	clang_visitChildren(cursor, Visit, nullptr);
	return CXChildVisit_Continue;
}

static void WriteOutput() {
	fs::path out = fs::path(g_baseDir) / "EVA" / "EVA.gen.cpp";

	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		return;
	}
	

	for (Type* type : g_types)
		if (type->shouldEmitTypeInfo)
			g_typesWeCareAbout.push_back(type);

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	for (const std::string& inc : g_includes) {
		fprintf(f, "#include <%s>\n", inc.c_str());
	}
	fprintf(f, "\n");

	for (Type* type : g_typesWeCareAbout) {
		fprintf(f, "extern Type g_type_%s;\n", type->symbolName.c_str());
	}
	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (Type* type : g_typesWeCareAbout) {
		std::string parent_ref = type->parent && type->parent->isObject ?  ("&g_type_" + type->parent->symbolName) : "nullptr";

		fprintf(f, "Type g_type_%s = {\n", type->symbolName.c_str());

		fprintf(f, "\t.name = \"%s\",\n", type->qualifiedName.c_str());
		fprintf(f, "\t.parent_type = %s,\n", parent_ref.c_str());

		if (type->subclasses.size()) {
			fprintf(f, "\t.subclasses = {\n");
			for (Type* subclass : type->subclasses) {
				fprintf(f, "\t\t&g_type_%s,\n", subclass->symbolName.c_str());
			};
			fprintf(f, "\t},\n");
		}
		if (type->isObject && !type->isAbstract) {
			fprintf(f,
				"\t.Instantiate = [](Allocator allocator) -> void* {\n"
				"\t\tvoid* ptr = (void*)allocator.Allocate(sizeof(%s), alignof(%s));\n"
				"\t\tnew (ptr) %s();\n"
				"\t\treturn ptr;\n"
				"\t},\n",
				type->qualifiedName.c_str(), type->qualifiedName.c_str(), type->qualifiedName.c_str());
		}
		fprintf(f, "};\n");
	}

	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (Type* type : g_types) {
		if (type->isObject) {
			fprintf(f, "Type* %s::StaticClass() { return &g_type_%s; }\n", type->qualifiedName.c_str(), type->symbolName.c_str());
			fprintf(f, "Type* %s::GetClass() { return &g_type_%s; }\n", type->qualifiedName.c_str(), type->symbolName.c_str());
		}
	}
	fprintf(f, "\n//------------------------------------------------------------\n\n");

	fprintf(f, "Type* Type::Find(String name) {\n");
	fprintf(f, "\tstatic Type* g_allTypes[] = {\n");
	for (Type* t : g_typesWeCareAbout) {
		fprintf(f, "\t\t&g_type_%s,\n", t->symbolName.c_str());
	}
	fprintf(f, "\t};\n");
	fprintf(f, "\tfor (Type* t : g_allTypes)\n");
	fprintf(f, "\t\tif (name == t->name) return t;\n");
	fprintf(f, "\treturn nullptr;\n");
	fprintf(f, "}\n");

	for (Type* type : g_typesWeCareAbout)
		for (Auto* _auto : type->autos)
			_auto->ForwardDeclare(f, type);
	fprintf(f, "\n\n");

	fclose(f);
}

int main() {
	std::vector<std::string> headers = CollectHeaders();

	printf("evagen: collected %zu headers\n", headers.size());
	std::string amalgam = WriteAmalgam(headers);

	std::string base = g_baseDir;
	std::vector<std::string> arg_strs = {
		"-x", "c++",
		"-std=c++20",
		"-DEVAGEN",
		"-I" + base,
		"-I" + base + "/Vendor/cglm-0.9.6/include",
		"-I" + base + "/Vendor/box3d/include",
		"-I" + base + "/Vendor/SDL-release-3.4.10/include",
		"-I" + base + "/Vendor/freetype-2.14.3/include",
		"-I" + base + "/Vendor/enet-1.3.18/include",
		"-I" + base + "/Vendor/volk",
	};

	if (const char* vulkanSdk = getenv("VULKAN_SDK"))
		arg_strs.push_back("-I" + std::string(vulkanSdk) + "/Include");
	std::vector<const char*> args;
	for (const std::string& s : arg_strs) args.push_back(s.c_str());

	CXIndex index = clang_createIndex(0, 0);

	CXTranslationUnit translationUnit = nullptr;
	CXErrorCode err = clang_parseTranslationUnit2(
		index, amalgam.c_str(), args.data(), (int)args.size(),
		nullptr, 0, CXTranslationUnit_SkipFunctionBodies | CXTranslationUnit_KeepGoing, &translationUnit);

	if (err != CXError_Success || !translationUnit) {
		fprintf(stderr, "evagen: failed to parse translation unit (err=%d)\n", (int)err);
		exit(1);
	}

	// Surface parse errors so we notice when the amalgam doesn't compile.
	unsigned num_diags = clang_getNumDiagnostics(translationUnit);
	for (unsigned i = 0; i < num_diags; ++i) {
		CXDiagnostic diag = clang_getDiagnostic(translationUnit, i);
		CXDiagnosticSeverity sev = clang_getDiagnosticSeverity(diag);
		if (sev >= CXDiagnostic_Error) {
			std::string text = CXStr(clang_formatDiagnostic(
				diag, clang_defaultDiagnosticDisplayOptions()));
			fprintf(stderr, "  %s\n", text.c_str());
		}
		clang_disposeDiagnostic(diag);
	}

	CXCursor root = clang_getTranslationUnitCursor(translationUnit);
	clang_visitChildren(root, Visit, nullptr);

	WriteOutput();
	return 0;
}
