// EVAGEN — EVA reflection generator.
//
// Walks EVA/ for .hpp files, emits a single amalgamated header that includes
// them all, then runs libclang over that one translation unit (instead of
// parsing ~200 compile units). For now it just logs struct/class definitions;
// the useful codegen comes later.

#include <clang-c/Index.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>

namespace fs = std::filesystem;

// Root that <EVA/...> includes resolve against, and the dir we walk.
static const char* kBaseDir    = "D:/EVA";
static const char* kEvaSubdir  = "EVA";

static std::string ToForwardSlashes(std::string s) {
	for (char& c : s) {
		if (c == '\\') c = '/';
	}
	return s;
}

// Collect every .hpp under EVA/ as a path relative to kBaseDir, using forward
// slashes so we can emit them as #include <EVA/...>.
static std::vector<std::string> CollectHeaders() {
	std::vector<std::string> headers;

	fs::path base = kBaseDir;
	fs::path walk = base / kEvaSubdir;

	for (const auto& entry : fs::recursive_directory_iterator(walk)) {
		if (!entry.is_regular_file()) continue;
		if (entry.path().extension() != ".hpp") continue;

		std::error_code ec;
		fs::path rel = fs::relative(entry.path(), base, ec);
		if (ec) rel = entry.path();

		headers.push_back(ToForwardSlashes(rel.string()));
	}

	// Deterministic ordering. #pragma once + explicit includes make the amalgam
	// order-independent, but stable output is nicer to diff.
	std::sort(headers.begin(), headers.end());
	return headers;
}

// Write the amalgamated header that pulls in every collected .hpp. Returns the
// path written, or empty on failure.
static std::string WriteAmalgam(const std::vector<std::string>& headers) {
	// Keep the generated file out of the source tree proper.
	fs::path out = fs::path(kBaseDir) / "EVAGEN" / "_amalgam.generated.hpp";

	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		return {};
	}

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	fprintf(f, "#pragma once\n");
	for (const std::string& h : headers) {
		fprintf(f, "#include <%s>\n", h.c_str());
	}
	fclose(f);

	return ToForwardSlashes(out.string());
}

static std::string CXStr(CXString s) {
	const char* c = clang_getCString(s);
	std::string out = c ? c : "";
	clang_disposeString(s);
	return out;
}

// Only report definitions that live inside our source tree, not system headers
// dragged in transitively.
static bool IsInOurTree(CXCursor cursor) {
	CXSourceLocation loc = clang_getCursorLocation(cursor);
	CXFile file;
	clang_getFileLocation(loc, &file, nullptr, nullptr, nullptr);
	if (!file) return false;

	std::string path = ToForwardSlashes(CXStr(clang_getFileName(file)));
	std::string base = ToForwardSlashes(std::string(kBaseDir) + "/" + kEvaSubdir + "/");
	return path.rfind(base, 0) == 0;
}

struct EClass {
	std::string name;
	std::string parent;
	std::string annotation;
	std::string header;
};

static std::vector<EClass> g_eclasses;

static std::string RelToBase(const std::string& path) {
	std::string base = ToForwardSlashes(std::string(kBaseDir)) + "/";
	if (path.rfind(base, 0) == 0) return path.substr(base.size());
	return path;
}

static std::string StripRecordKeyword(std::string s) {
	const char* prefixes[] = { "class ", "struct " };
	for (const char* p : prefixes) {
		size_t n = strlen(p);
		if (s.compare(0, n, p) == 0) { s.erase(0, n); break; }
	}
	return s;
}

struct RecordInfo {
	bool has_eclass = false;
	std::string annotation;
	std::string parent;
};

static CXChildVisitResult RecordChildVisitor(CXCursor c, CXCursor, CXClientData data) {
	RecordInfo* info = (RecordInfo*)data;
	CXCursorKind k = clang_getCursorKind(c);

	if (k == CXCursor_AnnotateAttr) {
		std::string s = CXStr(clang_getCursorSpelling(c));
		if (s.rfind("eclass", 0) == 0) {
			info->has_eclass = true;
			info->annotation = s;
		}
	} else if (k == CXCursor_CXXBaseSpecifier) {
		info->parent = StripRecordKeyword(CXStr(clang_getTypeSpelling(clang_getCursorType(c))));
	}
	return CXChildVisit_Continue;
}

static CXChildVisitResult Visit(CXCursor cursor, CXCursor /*parent*/, CXClientData /*data*/) {
	CXCursorKind kind = clang_getCursorKind(cursor);

	bool is_record = kind == CXCursor_StructDecl ||
	                 kind == CXCursor_ClassDecl;

	// Only actual definitions (skip forward declarations), and only ours.
	if (is_record && clang_isCursorDefinition(cursor) && IsInOurTree(cursor)) {
		const char* what = kind == CXCursor_ClassDecl ? "class" : "struct";

		CXSourceLocation loc = clang_getCursorLocation(cursor);
		CXFile file;
		unsigned line = 0;
		clang_getFileLocation(loc, &file, &line, nullptr, nullptr);

		std::string name = CXStr(clang_getCursorSpelling(cursor));
		std::string filename = ToForwardSlashes(CXStr(clang_getFileName(file)));

		RecordInfo info;
		clang_visitChildren(cursor, RecordChildVisitor, &info);

		printf("%-6s %-24s  %s:%u%s\n", what, name.c_str(), filename.c_str(), line,
		       info.has_eclass ? "  [ECLASS]" : "");

		if (info.has_eclass && !name.empty()) {
			EClass ec;
			ec.name = name;
			ec.parent = info.parent;
			ec.annotation = info.annotation;
			ec.header = RelToBase(filename);
			g_eclasses.push_back(ec);
		}
	}

	clang_visitChildren(cursor, Visit, nullptr);
	return CXChildVisit_Continue;
}

static void WriteGenFile(const std::vector<EClass>& eclasses) {
	fs::path out = fs::path(kBaseDir) / "EVA" / "EVA.gen.cpp";

	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		return;
	}

	std::vector<std::string> includes = { "EVA/Object.hpp" };
	for (const EClass& ec : eclasses) {
		if (std::find(includes.begin(), includes.end(), ec.header) == includes.end()) {
			includes.push_back(ec.header);
		}
	}

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	for (const std::string& inc : includes) {
		fprintf(f, "#include <%s>\n", inc.c_str());
	}
	fprintf(f, "\n");

	std::vector<std::string> names;
	for (const EClass& ec : eclasses) names.push_back(ec.name);
	auto is_eclass = [&](const std::string& n) {
		return std::find(names.begin(), names.end(), n) != names.end();
	};

	std::vector<const EClass*> ordered;
	std::vector<bool> emitted(eclasses.size(), false);
	bool progressed = true;
	while (progressed) {
		progressed = false;
		for (size_t i = 0; i < eclasses.size(); ++i) {
			if (emitted[i]) continue;
			const EClass& ec = eclasses[i];
			if (!is_eclass(ec.parent) ||
			    std::find_if(ordered.begin(), ordered.end(),
			                 [&](const EClass* e) { return e->name == ec.parent; }) != ordered.end()) {
				ordered.push_back(&ec);
				emitted[i] = true;
				progressed = true;
			}
		}
	}
	for (size_t i = 0; i < eclasses.size(); ++i) {
		if (!emitted[i]) ordered.push_back(&eclasses[i]);
	}

	for (const EClass* ec : ordered) {
		std::string parent_ref = is_eclass(ec->parent)
			? "&" + ec->parent + "::g_type"
			: "nullptr";
		fprintf(f, "Type %s::g_type = { %s, \"%s\" };\n",
		        ec->name.c_str(), parent_ref.c_str(), ec->name.c_str());
	}
	fprintf(f, "\n");

	for (const EClass* ec : ordered) {
		fprintf(f, "const Type& %s::GetType() { return %s::g_type; }\n",
		        ec->name.c_str(), ec->name.c_str());
	}

	fclose(f);
	printf("evagen: wrote %s (%zu eclasses)\n", out.string().c_str(), eclasses.size());
}

int main() {
	std::vector<std::string> headers = CollectHeaders();
	printf("evagen: collected %zu headers\n", headers.size());

	std::string amalgam = WriteAmalgam(headers);
	if (amalgam.empty()) return 1;

	std::string base = kBaseDir;
	std::vector<std::string> arg_strs = {
		"-x", "c++",
		"-std=c++20",
		"-DEVAGEN",
		"-I" + base,
		"-I" + base + "/Vendor/cglm-0.9.6/include",
		"-I" + base + "/Vendor/glad/include",
		"-I" + base + "/Vendor/box3d/include",
		"-I" + base + "/Vendor/SDL-release-3.4.10/include",
		"-I" + base + "/Vendor/freetype-2.14.3/include",
		"-I" + base + "/Vendor/enet-1.3.18/include",
	};
	std::vector<const char*> args;
	for (const std::string& s : arg_strs) args.push_back(s.c_str());

	CXIndex index = clang_createIndex(/*excludeDeclarationsFromPCH*/ 0,
	                                  /*displayDiagnostics*/ 0);

	CXTranslationUnit tu = nullptr;
	CXErrorCode err = clang_parseTranslationUnit2(
		index,
		amalgam.c_str(),
		args.data(), (int)args.size(),
		nullptr, 0,
		CXTranslationUnit_SkipFunctionBodies | CXTranslationUnit_KeepGoing,
		&tu);

	if (err != CXError_Success || !tu) {
		fprintf(stderr, "evagen: failed to parse translation unit (err=%d)\n", (int)err);
		clang_disposeIndex(index);
		return 1;
	}

	// Surface parse errors so we notice when the amalgam doesn't compile.
	unsigned num_diags = clang_getNumDiagnostics(tu);
	for (unsigned i = 0; i < num_diags; ++i) {
		CXDiagnostic diag = clang_getDiagnostic(tu, i);
		CXDiagnosticSeverity sev = clang_getDiagnosticSeverity(diag);
		if (sev >= CXDiagnostic_Error) {
			std::string text = CXStr(clang_formatDiagnostic(
				diag, clang_defaultDiagnosticDisplayOptions()));
			fprintf(stderr, "  %s\n", text.c_str());
		}
		clang_disposeDiagnostic(diag);
	}

	printf("----------------------------------------\n");
	CXCursor root = clang_getTranslationUnitCursor(tu);
	clang_visitChildren(root, Visit, nullptr);

	printf("----------------------------------------\n");
	WriteGenFile(g_eclasses);

	clang_disposeTranslationUnit(tu);
	clang_disposeIndex(index);
	return 0;
}
