#include <clang-c/Index.h>

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>

namespace fs = std::filesystem;

struct VersionChain;
struct Type;

struct Field {
	std::string type;
	std::string name;
};

struct EnumValue {
	std::string string;
	long long   value;
};

struct Type {
	std::string              name                  = "";
	std::string              qualifiedName         = "";
	std::string              symbolName            = "";
	Type*                    parent                = nullptr;
	std::vector<Type*>       subclasses            = {};
	std::string              header                = "'";
	std::vector<Field>       fields                = {};
	bool                     isObject              = false;
	bool                     isAbstract            = false;
	bool                     isEnum                = false;
	std::string              enumUnderlyingType    = "";
	std::vector<EnumValue>   enumValues            = {};
	std::vector<std::string> autos                 = {};
	int                      version               = 0;
	VersionChain*            versionChain          = nullptr;
	bool                     shouldEmitTypeInfo    = false;

	bool HasAuto(const std::string& name) const {
		return std::find(autos.begin(), autos.end(), name) != autos.end();
	}
};

struct VersionChain {
	std::string typeName;
	std::vector<Type*> versions;

	void Set(int version, Type* type) {
		if (versions.size() <= version) {
			versions.resize(version + 1);
		}
		versions[version] = type;
	}
};

// Root that <EVA/...> includes resolve against, and the dir we walk.
static const char* g_baseDir = "D:/EVA";
std::vector<std::string> g_includes = {
	"EVA/Core/Object.hpp",
	"EVA/Core/Serialization.hpp",
	"EVA/Core/Allocator.hpp"
};

static std::vector<Type*> g_types;
static std::vector<Type*> g_typesWeCareAbout;
static std::vector<VersionChain*> g_versionChains;


std::string TrimString(std::string s) {
    auto not_space = [](unsigned char c) { return !std::isspace(c); };
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), not_space));
    s.erase(std::find_if(s.rbegin(), s.rend(), not_space).base(), s.end());
    return s;
}

std::vector<std::string> SplitString(const std::string& s, char delimiter = ',') {
    std::vector<std::string> parts;
    std::stringstream ss(s);
    std::string part;
    while (std::getline(ss, part, delimiter))
        parts.push_back(part);
    return parts;
}


static std::string ToForwardSlashes(std::string s) {
	for (char& c : s) if (c == '\\') c = '/';
	return s;
}

static std::vector<std::string> CollectHeaders() {
	std::vector<std::string> headers;

	fs::path base = g_baseDir;
	fs::path walk = base / "EVA";

	for (const auto& entry : fs::recursive_directory_iterator(walk)) {
		if (!entry.is_regular_file()) continue;
		if (entry.path().extension() != ".hpp") continue;

		fs::path rel = fs::relative(entry.path(), base);
		headers.push_back(ToForwardSlashes(rel.string()));
	}

	std::sort(headers.begin(), headers.end());
	return headers;
}

static std::string WriteAmalgam(const std::vector<std::string>& headers) {
	fs::path out = fs::path(g_baseDir) / "EVAGEN" / "_amalgam.generated.hpp";

	_unlink(out.string().c_str());
	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		exit(1);
	}

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	fprintf(f, "#pragma once\n");
	for (const std::string& h : headers) {
		fprintf(f, "#include <%s>\n", h.c_str());
	}
	fclose(f);

	return ToForwardSlashes(out.string());
}

static std::string Str(CXString clangString) {
	const char* string = clang_getCString(clangString);
	std::string out = string ? string : "";
	clang_disposeString(clangString);
	return out;
}

// Only report definitions that live inside our source tree, not system headers
// dragged in transitively.
static bool IsInOurTree(CXCursor cursor) {
	CXSourceLocation loc = clang_getCursorLocation(cursor);
	CXFile file;
	clang_getFileLocation(loc, &file, nullptr, nullptr, nullptr);
	if (!file) return false;

	std::string path = ToForwardSlashes(Str(clang_getFileName(file)));
	std::string base = ToForwardSlashes(std::string(g_baseDir) + "/EVA/");
	return path.rfind(base, 0) == 0;
}

static std::string SymbolName(std::string name) {
	for (char& c : name) {
		if (!isalnum((unsigned char)c) && c != '_') c = '_';
	}
	return name;
}

static Type* GetType(const std::string& qualifiedName) {
	for (Type* type : g_types)
		if (type->qualifiedName == qualifiedName)
			return type;

	Type* type = new Type();
	type->qualifiedName = qualifiedName;
	size_t separator = qualifiedName.rfind("::");
	type->name = separator == std::string::npos ? qualifiedName : qualifiedName.substr(separator + 2);
	type->symbolName = SymbolName(qualifiedName);
	g_types.push_back(type);
	return type;
}

static std::string RelToBase(const std::string& path) {
	std::string base = ToForwardSlashes(std::string(g_baseDir)) + "/";
	if (path.rfind(base, 0) == 0) return path.substr(base.size());
	return path;
}

static std::string StripRecordKeyword(std::string s) {
	const char* prefixes[] = { "class ", "struct " };
	for (const char* p : prefixes) {
		size_t n = strlen(p);
		if (s.compare(0, n, p) == 0) { s.erase(0, n); break; }
	}
	return s;
}

static CXChildVisitResult AnnotationVisitor(CXCursor cursor, CXCursor, CXClientData data) {
	if (clang_getCursorKind(cursor) != CXCursor_AnnotateAttr)
		return CXChildVisit_Continue;

	auto* annotations = static_cast<std::vector<std::string>*>(data);
	annotations->push_back(Str(clang_getCursorSpelling(cursor)));
	return CXChildVisit_Continue;
}

static bool HasAnnotation(CXCursor cursor, const std::string& annotation) {
	std::vector<std::string> annotations;
	clang_visitChildren(cursor, AnnotationVisitor, &annotations);
	return std::find(annotations.begin(), annotations.end(), annotation) != annotations.end();
}

static Type* GetTypeFromCXType(CXType valueType) {
	valueType = clang_getCanonicalType(valueType);
	if (valueType.kind == CXType_LValueReference || valueType.kind == CXType_RValueReference)
		valueType = clang_getPointeeType(valueType);

	CXCursor declaration = clang_getTypeDeclaration(valueType);
	if (clang_Cursor_isNull(declaration))
		return nullptr;

	std::string qualifiedName = StripRecordKeyword(Str(clang_getTypeSpelling(clang_getCursorType(declaration))));
	return qualifiedName.empty() ? nullptr : GetType(qualifiedName);
}

static Type* GetAutoType(CXCursor cursor, const std::string& name) {
	if (name == "Serialize" || name == "Deserialize") {
		if (clang_Cursor_getNumArguments(cursor) < 2)
			return nullptr;
		return GetTypeFromCXType(clang_getCursorType(clang_Cursor_getArgument(cursor, 1)));
	}
	if (name == "ToString") {
		if (clang_Cursor_getNumArguments(cursor) < 1)
			return nullptr;
		return GetTypeFromCXType(clang_getCursorType(clang_Cursor_getArgument(cursor, 0)));
	}
	if (name == "FromString")
		return GetTypeFromCXType(clang_getCursorResultType(cursor));
	return nullptr;
}

static void CollectAuto(CXCursor cursor) {
	if (!HasAnnotation(cursor, "eauto"))
		return;

	std::string name = Str(clang_getCursorSpelling(cursor));
	if (name != "Serialize" && name != "Deserialize" && name != "ToString" && name != "FromString")
		return;

	Type* type = GetAutoType(cursor, name);
	if (type && std::find(type->autos.begin(), type->autos.end(), name) == type->autos.end())
		type->autos.push_back(name);
}

static void FinalizeAutos() {
	for (Type* type : g_types) {
		bool hasSerialize = type->HasAuto("Serialize");
		bool hasDeserialize = type->HasAuto("Deserialize");
		bool hasToString = type->HasAuto("ToString");
		bool hasFromString = type->HasAuto("FromString");
		type->autos.clear();
		if (hasSerialize && hasDeserialize)
			type->autos.insert(type->autos.end(), { "Serialize", "Deserialize" });
		if (type->isEnum && hasToString && hasFromString)
			type->autos.insert(type->autos.end(), { "ToString", "FromString" });

		if (type->isEnum && !type->autos.empty()) {
			type->shouldEmitTypeInfo = true;
			if (std::find(g_includes.begin(), g_includes.end(), type->header) == g_includes.end())
				g_includes.push_back(type->header);
		}
	}
}

static CXChildVisitResult FieldAnnotationVisitor(CXCursor c, CXCursor, CXClientData data) {
	// bool* is_prop = (bool*)data;
	// if (clang_getCursorKind(c) == CXCursor_AnnotateAttr) {
	// 	std::string s = Str(clang_getCursorSpelling(c));
	// 	if (s.rfind("eproperty", 0) == 0) *is_prop = true;
	// }
	return CXChildVisit_Continue;
}

VersionChain* GetVersionChain(const std::string& name) {
	for (VersionChain* chain : g_versionChains) {
		if (chain->typeName == name)
			return chain;
	}
	VersionChain* chain = new VersionChain();
	chain->typeName = name;
	g_versionChains.push_back(chain);

	return chain;
}

static CXChildVisitResult RecordChildVisitor(CXCursor cursor, CXCursor, void* _type) {
	Type* type = (Type*)_type;
	CXCursorKind kind = clang_getCursorKind(cursor);

	if (kind == CXCursor_AnnotateAttr) {
		std::string annotation = Str(clang_getCursorSpelling(cursor));
		std::vector<std::string> args = SplitString(annotation, ',');
		for (std::string& arg : args)
			arg = TrimString(arg);

		if (args[0] == "eversion") {
			type->version = std::stoi(args[1]);
			if (args.size() >= 3)
				type->versionChain = GetVersionChain(args[2]);
			else
				type->versionChain = GetVersionChain(type->symbolName);
			type->versionChain->Set(type->version, type);
		}
	} else if (kind == CXCursor_CXXBaseSpecifier) {
		CXType base_type = clang_getCanonicalType(clang_getCursorType(cursor));
		type->parent = GetType(StripRecordKeyword(Str(clang_getTypeSpelling(base_type))));
		type->parent->subclasses.push_back(type);
	} else if (kind == CXCursor_FieldDecl) {
		// clang_visitChildren(cursor, FieldAnnotationVisitor, &is_prop);
			type->fields.push_back(Field {
			.type = "", // TODO
			.name = Str(clang_getCursorSpelling(cursor)),
		});
	} else if (kind == CXCursor_EnumConstantDecl) {
		type->enumValues.push_back(EnumValue {
			.string = Str(clang_getCursorSpelling(cursor)),
			.value = clang_getEnumConstantDeclValue(cursor),
		});
	}
	return CXChildVisit_Continue;
}

static CXChildVisitResult Visit(CXCursor cursor, CXCursor parent, void* userdata) {
	CXCursorKind kind = clang_getCursorKind(cursor);
	if (kind == CXCursor_FunctionDecl && IsInOurTree(cursor))
		CollectAuto(cursor);

	bool is_record = kind == CXCursor_StructDecl || kind == CXCursor_ClassDecl;
	bool isEnum   = kind == CXCursor_EnumDecl;

	// only actual definitions, and only ours:
	if ((is_record || isEnum) && clang_isCursorDefinition(cursor) && IsInOurTree(cursor)) {
		CXSourceLocation loc = clang_getCursorLocation(cursor);
		CXFile file;
		unsigned line = 0;
		clang_getFileLocation(loc, &file, &line, nullptr, nullptr);

		std::string name          = Str(clang_getCursorSpelling(cursor));
		std::string qualifiedName = StripRecordKeyword(Str(clang_getTypeSpelling(clang_getCursorType(cursor))));
		std::string filename      = ToForwardSlashes(Str(clang_getFileName(file)));

		Type* type = GetType(qualifiedName);
		clang_visitChildren(cursor, RecordChildVisitor, type);
		type->isAbstract = clang_CXXRecord_isAbstract(cursor);
		type->isObject = qualifiedName == "Object" || (type->parent && type->parent->isObject);
		type->header = RelToBase(filename);
		type->isEnum = isEnum;

		if (type->isObject) {
			g_typesWeCareAbout.push_back(type);
			g_includes.push_back(filename);
		}

		if (isEnum) 
			type->enumUnderlyingType = Str(clang_getTypeSpelling(clang_getEnumDeclIntegerType(cursor)));
	}

	clang_visitChildren(cursor, Visit, nullptr);
	return CXChildVisit_Continue;
}

static void WriteOutput() {
	fs::path out = fs::path(g_baseDir) / "EVA" / "EVA.gen.cpp";

	FILE* f = fopen(out.string().c_str(), "wb");
	if (!f) {
		fprintf(stderr, "evagen: failed to open %s for writing\n", out.string().c_str());
		return;
	}
	

	for (Type* type : g_types)
		if (type->shouldEmitTypeInfo)
			g_typesWeCareAbout.push_back(type);

	fprintf(f, "// GENERATED BY EVAGEN. DO NOT EDIT.\n");
	for (const std::string& inc : g_includes) {
		fprintf(f, "#include <%s>\n", inc.c_str());
	}
	fprintf(f, "\n");

	for (Type* type : g_typesWeCareAbout) {
		fprintf(f, "extern %s g_type_%s;\n", type->isEnum ? "EnumType" : "Type", type->symbolName.c_str());
	}
	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (Type* type : g_typesWeCareAbout) {
		std::string parent_ref = type->parent && type->parent->isObject ?  ("&g_type_" + type->parent->symbolName) : "nullptr";
		if (type->isEnum) {
			fprintf(f, "EnumType g_type_%s {\n", type->symbolName.c_str());
			fprintf(f, "\t\"%s\",\n", type->qualifiedName.c_str());
			fprintf(f, "\t{\n");
			for (const EnumValue& value : type->enumValues)
				fprintf(f, "\t\t{ \"%s\", %lld },\n", value.string.c_str(), value.value);
			fprintf(f, "\t},\n");
			fprintf(f, "};\n");
			continue;
		}

		fprintf(f, "Type g_type_%s = {\n", type->symbolName.c_str());

		fprintf(f, "\t.name = \"%s\",\n", type->qualifiedName.c_str());
		fprintf(f, "\t.parent_type = %s,\n", parent_ref.c_str());

		if (type->subclasses.size()) {
			fprintf(f, "\t.subclasses = {\n");
			for (Type* subclass : type->subclasses) {
				fprintf(f, "\t\t&g_type_%s,\n", subclass->symbolName.c_str());
			};
			fprintf(f, "\t},\n");
		}
		if (type->isObject && !type->isAbstract) {
			fprintf(f,
				"\t.Instantiate = [](Allocator allocator) -> void* {\n"
				"\t\tvoid* ptr = (void*)allocator.Allocate(sizeof(%s), alignof(%s));\n"
				"\t\tnew (ptr) %s();\n"
				"\t\treturn ptr;\n"
				"\t},\n",
				type->qualifiedName.c_str(), type->qualifiedName.c_str(), type->qualifiedName.c_str());
		}
		fprintf(f, "};\n");
	}

	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (Type* type : g_typesWeCareAbout) {
		if (!type->isEnum || !type->HasAuto("ToString"))
			continue;

		fprintf(f, "ZTString ToString(%s& t) {\n", type->qualifiedName.c_str());
		fprintf(f, "\tfor (const EnumValue& value : g_type_%s.values)\n", type->symbolName.c_str());
		fprintf(f, "\t\tif (value.value == (I64)t) return value.string;\n");
		fprintf(f, "\treturn {};\n");
		fprintf(f, "}\n");

		fprintf(f, "template<> %s FromString<%s>(String str) {\n", type->qualifiedName.c_str(), type->qualifiedName.c_str());
		fprintf(f, "\tfor (const EnumValue& value : g_type_%s.values)\n", type->symbolName.c_str());
		fprintf(f, "\t\tif (value.string == str) return (%s)value.value;\n", type->qualifiedName.c_str());
		fprintf(f, "\treturn {};\n");
		fprintf(f, "}\n");

		if (type->HasAuto("Serialize")) {
			fprintf(f, "void Serialize(Serializer& s, const %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\tif (s.IsText()) {\n");
			fprintf(f, "\t\t%s textValue = value;\n", type->qualifiedName.c_str());
			fprintf(f, "\t\ts.SerializeString(ToString(textValue));\n");
			fprintf(f, "\t} else {\n");
			fprintf(f, "\t\t%s underlyingValue = (%s)value;\n", type->enumUnderlyingType.c_str(), type->enumUnderlyingType.c_str());
			fprintf(f, "\t\tSerialize(s, underlyingValue);\n");
			fprintf(f, "\t}\n");
			fprintf(f, "}\n");

			fprintf(f, "void Deserialize(Deserializer& d, %s& value) {\n", type->qualifiedName.c_str());
			fprintf(f, "\tif (d.IsText()) {\n");
			fprintf(f, "\t\tvalue = FromString<%s>(d.DeserializeString());\n", type->qualifiedName.c_str());
			fprintf(f, "\t} else {\n");
			fprintf(f, "\t\t%s underlyingValue = {};\n", type->enumUnderlyingType.c_str());
			fprintf(f, "\t\tDeserialize(d, underlyingValue);\n");
			fprintf(f, "\t\tvalue = (%s)underlyingValue;\n", type->qualifiedName.c_str());
			fprintf(f, "\t}\n");
			fprintf(f, "}\n");
		}
	}

	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (Type* type : g_types) {
		if (type->isObject) {
			fprintf(f, "Type* %s::StaticClass() { return &g_type_%s; }\n", type->qualifiedName.c_str(), type->symbolName.c_str());
			fprintf(f, "Type* %s::GetClass() { return &g_type_%s; }\n", type->qualifiedName.c_str(), type->symbolName.c_str());
		}
	}
	fprintf(f, "\n//------------------------------------------------------------\n\n");

	fprintf(f, "Type* Type::Find(String name) {\n");
	fprintf(f, "\tstatic Type* g_allTypes[] = {\n");
	for (Type* t : g_typesWeCareAbout) {
		fprintf(f, "\t\t&g_type_%s,\n", t->symbolName.c_str());
	}
	fprintf(f, "\t};\n");
	fprintf(f, "\tfor (Type* t : g_allTypes)\n");
	fprintf(f, "\t\tif (name == t->name) return t;\n");
	fprintf(f, "\treturn nullptr;\n");
	fprintf(f, "}\n");

	fprintf(f, "\n//------------------------------------------------------------\n\n");

	for (VersionChain* chain : g_versionChains) {
		Type* latest = chain->versions[chain->versions.size() - 1];
		if (!latest->HasAuto("Serialize"))
			continue;

		for (int i = 1; i < chain->versions.size(); i++) {
			Type* current = chain->versions[i];
			Type* prev = chain->versions[i - 1];

			if (current && prev) {
				fprintf(f, "void Convert(const %s& oldValue, %s& newValue);\n", prev->qualifiedName.c_str(), current->qualifiedName.c_str());
			}
		}
	}
	fprintf(f, "\n");

	for (VersionChain* chain : g_versionChains) {
		Type* latest = chain->versions[chain->versions.size() - 1];
		if (!latest->HasAuto("Serialize"))
			continue;

		fprintf(f, "void Serialize(Serializer& s, const %s& value) {\n", latest->qualifiedName.c_str());
		fprintf(f, "	s.BeginObject();\n");
		fprintf(f, "	s.Key(\"version\");\n");
		fprintf(f, "	s.SerializeU32(%u);\n", latest->version);

		for (const Field& field : latest->fields) {
			fprintf(f, "	s.Key(\"%s\");\n", field.name.c_str());
			fprintf(f, "	Serialize(s, value.%s);\n", field.name.c_str());
		}
		fprintf(f, "	s.EndObject();\n");
		fprintf(f, "}\n");


		fprintf(f, "void Deserialize(Deserializer& d, %s& v%u) {\n", latest->qualifiedName.c_str(), latest->version);
		fprintf(f, "	d.BeginObject();\n");
		fprintf(f, "	d.Key(\"version\");\n");
		fprintf(f, "	U32 version = d.DeserializeU32();\n");
		fprintf(f, "	switch (version) {\n");

		for (Type* type : chain->versions) {
			if (!type) continue;

			fprintf(f, "		case %u: {\n", type->version);

			for (int v = type->version; v < chain->versions.size() - 1; v++) {
				fprintf(f, "			%s v%u;\n", chain->versions[v]->qualifiedName.c_str(), v);
			};
			for (const Field& field : type->fields) {
				fprintf(f, "			d.Key(\"%s\");\n", field.name.c_str());
				fprintf(f, "			Deserialize(d, v%u.%s);\n", type->version, field.name.c_str());
			}
			for (int v = type->version; v < chain->versions.size() - 1; v++) {
				fprintf(f, "			Convert(v%u, v%u);\n", v, v + 1);
			};

			fprintf(f, "			break;\n");
			fprintf(f, "		}\n");
		}
		fprintf(f, "	};\n");

		fprintf(f, "	d.EndObject();\n");
		fprintf(f, "}\n");

	}

	fclose(f);
}

int main() {
	std::vector<std::string> headers = CollectHeaders();

	printf("evagen: collected %zu headers\n", headers.size());
	std::string amalgam = WriteAmalgam(headers);

	std::string base = g_baseDir;
	std::vector<std::string> arg_strs = {
		"-x", "c++",
		"-std=c++20",
		"-DEVAGEN",
		"-I" + base,
		"-I" + base + "/Vendor/cglm-0.9.6/include",
		"-I" + base + "/Vendor/box3d/include",
		"-I" + base + "/Vendor/SDL-release-3.4.10/include",
		"-I" + base + "/Vendor/freetype-2.14.3/include",
		"-I" + base + "/Vendor/enet-1.3.18/include",
		"-I" + base + "/Vendor/volk",
	};

	if (const char* vulkanSdk = getenv("VULKAN_SDK"))
		arg_strs.push_back("-I" + std::string(vulkanSdk) + "/Include");
	std::vector<const char*> args;
	for (const std::string& s : arg_strs) args.push_back(s.c_str());

	CXIndex index = clang_createIndex(0, 0);

	CXTranslationUnit translationUnit = nullptr;
	CXErrorCode err = clang_parseTranslationUnit2(
		index, amalgam.c_str(), args.data(), (int)args.size(),
		nullptr, 0, CXTranslationUnit_SkipFunctionBodies | CXTranslationUnit_KeepGoing, &translationUnit);

	if (err != CXError_Success || !translationUnit) {
		fprintf(stderr, "evagen: failed to parse translation unit (err=%d)\n", (int)err);
		exit(1);
	}

	// Surface parse errors so we notice when the amalgam doesn't compile.
	unsigned num_diags = clang_getNumDiagnostics(translationUnit);
	bool hasCompileError = false;
	for (unsigned i = 0; i < num_diags; ++i) {
		CXDiagnostic diag = clang_getDiagnostic(translationUnit, i);
		CXDiagnosticSeverity sev = clang_getDiagnosticSeverity(diag);
		if (sev >= CXDiagnostic_Error) {
			std::string text = Str(clang_formatDiagnostic(diag, clang_defaultDiagnosticDisplayOptions()));
			fprintf(stderr, "  %s\n", text.c_str());
			hasCompileError = true;
		}
		clang_disposeDiagnostic(diag);
	}
	if (hasCompileError) exit(1);

	CXCursor root = clang_getTranslationUnitCursor(translationUnit);
	clang_visitChildren(root, Visit, nullptr);
	FinalizeAutos();

	WriteOutput();
	return 0;
}
